<?php
/** @var Laminas\View\Renderer\PhpRenderer $this */
/** @var ConLayout\Ldt\Collector\LayoutCollector $collector */
$dump = function_exists('dump') ? 'dump': 'var_export';
$collectedFiles = $collector->getCollectedFiles();
?>
<div class="laminas-toolbar-entry laminas-conlayout-entry">
    <div class="laminas-toolbar-preview">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABXUlEQVRIS2NkoDFgpLH5DGALdh04HMjEyDyDkYlRjBoW/vv//zXDn/+prk7WG8EW7Dl47CXz1FYxRkYmhr85VQydH9YxMP1nZCgVDGTQfpgPVMHEcFW+nyS7///7/8rF3kocbMHew8f/M09pYwCayfAvu4qh+/16BgZGoAUCAUALCoHiTAzX5HpJsgCk2NnWEmgK1AKSdROhAW7Bmw8f/xOhnmQlIgL8EB/QzYJbd+4xfP/+A+xSLi5OBlVlRTAbWZyQN5D1Yfjg4uVrKPr1dbXA/Nt37zN8+/adkNlgeW5uLgYVJQUwm2gLiDIZi6LBYwHN4wA9bggFGSzuiA6iUQvgORlXPhg6QYScY5FzJMU5+eWbt/+ZWVgIpT6S5P/8+cMgISIMKU1PXbj8UU5Gio+FSpaADH/0+NkHM0NdQbAFu/cd9WdkZpxFrTr5/99/L/8y/Et1d7DdTPNWBQAu59kZuoTsCwAAAABJRU5ErkJggg==">
        <span class="laminas-toolbar-info">Layout</span>
    </div>
    <div class="laminas-toolbar-detail laminas-toolbar-detail-overflow" id="laminas-conlayout-content">
        <div class="laminas-toolbar-info">
            <span class="laminas-detail-label">Current Area</span>
            <span class="laminas-detail-value"><?= $this->escapeHtml($collector->getCurrentArea()) ?></span>
        </div>
        <span class="laminas-toolbar-info">
            <span class="laminas-toolbar-info laminas-toolbar-info-heading">Merged layout instructions</span>
            <span class="laminas-detail-pre"><?php ($dump)($collector->getLayoutStructure()); ?></span>
        </span>
        <span class="laminas-toolbar-info">
            <span class="laminas-toolbar-info laminas-toolbar-info-heading">Loaded blocks</span>
            <?php $loadedBlocks = $collector->getBlocks() ?>
            <?php if (!count($loadedBlocks)): ?>
            <span class="laminas-detail-value">N/A</span>
            <span class="clear"></span>
            <?php else: ?>
            <table class="table table-sm table-condensed table-dark">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Capture to</th>
                        <th>Template</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($loadedBlocks as $blockId => $block): ?>
                    <tr>
                        <td>
                            <?= $this->escapeHtml($blockId) ?>
                        </td>
                        <td>
                            <?= $this->escapeHtml($block['capture_to']) ?>
                        </td>
                        <td>
                            <?php if ($remoteCall = $collector->getRemoteCall()): ?>
                                <a href="<?= $this->escapeHtml($collector->getRemoteCallUrl($block['template'])) ?>">
                                    <?= $this->escapeHtml($block['template']) ?>
                                </a>
                            <?php else: ?>
                                <?= $this->escapeHtml($block['template']) ?>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php endif; ?>
        </span>
        <div class="laminas-toolbar-info">
            <span class="laminas-toolbar-info laminas-toolbar-info-heading">Handles</span>
            <table class="table table-sm table-condensed table-dark">
                <thead>
                    <tr>
                        <th>Handle name</th>
                        <th>Priority</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($collector->getHandles() as $handle): ?>
                   <tr>
                       <td><?= $this->escapeHtml($handle->getName()) ?></td>
                       <td><?= (int) $handle->getPriority() ?></td>
                   </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="laminas-toolbar-info">
            <table class="table table-sm table-dark">
                <thead>
                    <tr>
                        <th>Handle</th>
                        <th>Collected files</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($collectedFiles as $handle => $files): ?>
                    <tr>
                        <td><?= $this->escapeHtml($handle) ?></td>
                        <td>
                            <ol>
                                <?php foreach ($files as $file): ?>
                                <li>
                                    <?php if ($remoteCall = $collector->getRemoteCall()): ?>
                                        <a href="<?= $this->escapeHtml($collector->getRemoteCallUrl($file)) ?>">
                                            <?= $this->escapeHtml($file) ?>
                                        </a>
                                    <?php else: ?>
                                        <?= $this->escapeHtml($file) ?>
                                    <?php endif ?>
                                </li>
                                <?php endforeach; ?>
                            </ol>

                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
