<div 
    class="block-debug" 
    data-block-name="<?php echo $this->blockName ?>"
    data-block-template="<?php echo $this->blockTemplate ?>"
    data-block-class="<?php echo $this->blockClass ?>"
>
    <span class="block-debug-info">
        <span><?php echo $this->blockName ?></span>
        <span><?php echo $this->blockTemplate ?></span>
        <span><?php echo $this->blockClass ?></span>
    </span>
    <?php echo $this->content ?>
</div>
