<?php
use ConLayout\Debug\Debugger;
$blockName = Debugger::VAR_BLOCK_NAME;
$blockTpl  = Debugger::VAR_BLOCK_TPL;
$blockClass = Debugger::VAR_BLOCK_CLASS;
$blockType  = Debugger::VAR_BLOCK_TYPE;
?>
<div
    class="block-debug block-type-<?= $this->{$blockType} ?>"
    data-block-name="<?= $this->{$blockName} ?>"
    data-block-template="<?= $this->{$blockTpl} ?>"
    data-block-class="<?= $this->{$blockClass} ?>"
>
    <span class="block-debug-info">
        <span><?= $this->{$blockName} ?></span>
        <span><?= $this->{$blockTpl} ?></span>
        <span><?= $this->{$blockClass} ?></span>
    </span>
    <?= $this->content ?>
</div>
