<div 
    class="block-debug block-type-<?= $this->blockType ?>"
    data-block-name="<?= $this->blockName ?>"
    data-block-template="<?= $this->blockTemplate ?>"
    data-block-class="<?= $this->blockClass ?>"
>
    <span class="block-debug-info">
        <span><?= $this->blockName ?></span>
        <span><?= $this->blockTemplate ?></span>
        <span><?= $this->blockClass ?></span>
    </span>
    <?= $this->content ?>
</div>
