language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
before_script:
  - composer self-update
  - composer update --prefer-source
  
script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ConLayoutTest/

after_script:
  - ./vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 7.0
