<div class="collapse navbar-collapse navbar-ex4-collapse">
    <nav class="navigation">
    <?php 
    echo $this->navigation('navigation')
        ->menu()
        ->setUlClass('nav navbar-nav')
        ->setMaxDepth(0)
        ->setRenderInvisible(false);
    ?>
    </nav>
    <?php if ($this->zfcUserIdentity()): ?>
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                  <a href="<?php echo $this->url('zfcuser/logout') ?>">
                      <i class="glyphicon glyphicon-off"></i>
                      <?php echo $this->__('Logout') ?>
                  </a>
              </li>
            </ul>
        </li>
    </ul>
    <?php endif; ?>
</div>
