<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->head ?>
    </head>
    <body class="layout-2cols-right">
        <?= $this->header ?>
        <div class="container">
            <div class="row">
                <section class="content col-sm-9">
                    <?= $this->flashMessenger()->render() ?>
                    <?= $this->content; ?>
                </section>
                <aside class="sidebar col-sm-3">
                    <?= $this->sidebarPrimary ?>
                </aside>
            </div>
            <?= $this->footer ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
