<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->head ?>
    </head>
    <body class="layout-2cols-left">
        <?= $this->header ?>
        <div class="container">
            <div class="row">
                <section class="content col-sm-push-3 col-sm-9">
                    <?= $this->flashMessenger()->render() ?>
                    <?= $this->content ?>
                </section>
                <aside class="sidebar col-sm-pull-9 col-sm-3">
                    <?= $this->sidebarPrimary ?>
                </aside>
            </div>
            <?= $this->footer ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
