<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body class="layout-3cols">
        <?= $this->header ?>
        <div class="container">
            <div class="row">
                <aside class="sidebar primary col-sm-3">
                    <?= $this->sidebarLeft ?>
                </aside>
                <section class="content col-sm-6">
                    <?= $this->breadcrumbs ?>
                    <?= $this->flashMessenger()->render() ?>
                    <?= $this->content ?>
                </section>
                <aside class="sidebar secondary col-sm-3">
                    <?= $this->sidebarRight ?>
                </aside>
            </div>
            <?= $this->footer ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
