<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->head ?>
    </head>
    <body class="layout-empty">
        <div class="container">
            <div class="row">
                <section class="content col-sm-12">
                    <?= $this->flashMessenger()->render() ?>
                    <?= $this->content ?>
                </section>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
