<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body class="layout-1col">
        <?= $this->header ?>
        <div class="container">
            <div class="row">
                <section class="content col-sm-12">
                    <?= $this->breadcrumbs ?>
                    <?= $this->flashMessenger()->render() ?>
                    <?= $this->content ?>
                </section>
            </div>
            <?= $this->footer ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
