<?php /* @var $collector ConLayout\Collector\LayoutCollector */ ?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">            
        <img style="width:22px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABXUlEQVRIS2NkoDFgpLH5DGALdh04HMjEyDyDkYlRjBoW/vv//zXDn/+prk7WG8EW7Dl47CXz1FYxRkYmhr85VQydH9YxMP1nZCgVDGTQfpgPVMHEcFW+nyS7///7/8rF3kocbMHew8f/M09pYwCayfAvu4qh+/16BgZGoAUCAUALCoHiTAzX5HpJsgCk2NnWEmgK1AKSdROhAW7Bmw8f/xOhnmQlIgL8EB/QzYJbd+4xfP/+A+xSLi5OBlVlRTAbWZyQN5D1Yfjg4uVrKPr1dbXA/Nt37zN8+/adkNlgeW5uLgYVJQUwm2gLiDIZi6LBYwHN4wA9bggFGSzuiA6iUQvgORlXPhg6QYScY5FzJMU5+eWbt/+ZWVgIpT6S5P/8+cMgISIMKU1PXbj8UU5Gio+FSpaADH/0+NkHM0NdQbAFu/cd9WdkZpxFrTr5/99/L/8y/Et1d7DdTPNWBQAu59kZuoTsCwAAAABJRU5ErkJggg==">
        <span class="zdt-toolbar-info">Layout</span>
    </div>
    <div class="zdt-toolbar-detail" style="right: 0">
        <span class="zdt-toolbar-info zdt-toolbar-info-heading">
            Layout config
        </span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-pre">
                <?php \Zend\Debug\Debug::dump($collector->getLayoutConfig()); ?>
            </span>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-toolbar-info zdt-toolbar-info-heading">
                Loaded blocks (view models)
            </span>
            <?php $loadedBlocks = $collector->getBlocks() ?>
            <?php if (!count($loadedBlocks)): ?>
            <span class="zdt-detail-value">
                N/A
            </span>
            <span class="clear"></span>
            <?php else: ?>
            <?php foreach ($loadedBlocks as $blockName => $instanceName): ?>
            <span data-block-name-label="<?php echo $blockName ?>" class="zdt-detail-label" style="text-transform: none !important;cursor: pointer">
                <?php echo $blockName ?>
            </span>
            <span class="zdt-detail-value">
                <?php echo $instanceName ?>
            </span><br>
            <?php endforeach; ?>
            <?php endif; ?>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Handles</span>
            <?php foreach($collector->getHandles() as $i => $handle): ?>
            <span class="zdt-detail-value<?php echo $i > 0 ? ' zdt-detail-extra-value' : '' ?>">
                <?php echo $handle ?>
            </span><br>
            <?php endforeach; ?>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Layout Template</span>
            <span class="zdt-detail-value"><?php echo $collector->getLayoutTemplate() ?></span>
        </span>
    </div>
</div>
<script>
    jQuery(function($) {
        $('[data-block-name-label]').on('mouseenter', function() {
            $('[data-block-name="' + $(this).data('blockNameLabel') + '"]').addClass('block-highlight')
        }).on('mouseleave', function() {
            if (!$(this).hasClass('toggled')) {
                $('[data-block-name="' + $(this).data('blockNameLabel') + '"]').removeClass('block-highlight');
            }
        }).on('click', function() {
            $('[data-block-name-label]')
                .not($(this)).removeClass('toggled');
            $(this).toggleClass('toggled');
            $('[data-block-name]').not($('[data-block-name="' + $(this).data('blockNameLabel') + '"]'))
                .removeClass('block-highlight');
        });
    });
</script>
