<?php /* @var $collector ConLayout\Zdt\Collector\LayoutCollector */ ?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">           
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABXUlEQVRIS2NkoDFgpLH5DGALdh04HMjEyDyDkYlRjBoW/vv//zXDn/+prk7WG8EW7Dl47CXz1FYxRkYmhr85VQydH9YxMP1nZCgVDGTQfpgPVMHEcFW+nyS7///7/8rF3kocbMHew8f/M09pYwCayfAvu4qh+/16BgZGoAUCAUALCoHiTAzX5HpJsgCk2NnWEmgK1AKSdROhAW7Bmw8f/xOhnmQlIgL8EB/QzYJbd+4xfP/+A+xSLi5OBlVlRTAbWZyQN5D1Yfjg4uVrKPr1dbXA/Nt37zN8+/adkNlgeW5uLgYVJQUwm2gLiDIZi6LBYwHN4wA9bggFGSzuiA6iUQvgORlXPhg6QYScY5FzJMU5+eWbt/+ZWVgIpT6S5P/8+cMgISIMKU1PXbj8UU5Gio+FSpaADH/0+NkHM0NdQbAFu/cd9WdkZpxFrTr5/99/L/8y/Et1d7DdTPNWBQAu59kZuoTsCwAAAABJRU5ErkJggg==">
        <span class="zdt-toolbar-info">Layout</span>
    </div>
    <div class="zdt-toolbar-detail" style="right: 0; max-width: 38%">
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-pre">
                <?php \Zend\Debug\Debug::dump($collector->getLayoutStructure()); ?>
            </span>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-toolbar-info zdt-toolbar-info-heading">
                Loaded blocks (view models)
            </span>
            <?php $loadedBlocks = $collector->getBlocks() ?>
            <?php if (!count($loadedBlocks)): ?>
            <span class="zdt-detail-value">
                N/A
            </span>
            <span class="clear"></span>
            <?php else: ?>
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Class</th>
                        <th>Capture to</th>
                        <th>Template</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($loadedBlocks as $blockName => $block): ?>
                    <tr>
                        <td style="text-transform: none !important;cursor: pointer" data-block-name-label="<?= $blockName ?>">
                            <?= $blockName ?>
                        </td>
                        <td>
                            <?= get_class($block) ?>
                        </td>
                        <td>
                            <?= $block->getVariable('captureTo') 
                                ? $block->getVariable('captureTo')
                                : $block->captureTo()
                            ?>
                        </td>
                        <td>
                            <?= $block->getTemplate() ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php endif; ?>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-toolbar-info zdt-toolbar-info-heading">Handles</span>
             <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Handle name</th>
                        <th>Priority</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($collector->getHandles() as $handle): ?>
                   <tr>
                       <td><?= $handle->getName() ?></td>
                       <td><?= $handle->getPriority() ?></td>
                   </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </span>
        <hr>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Layout Template</span>
            <span class="zdt-detail-value"><?= $collector->getLayoutTemplate() ?></span>
        </span>
    </div>
</div>
<script>
    jQuery(function($) {
        $('[data-block-name-label]').on('mouseenter', function() {
            $('[data-block-name="' + $(this).data('blockNameLabel') + '"]').addClass('block-highlight')
        }).on('mouseleave', function() {
            if (!$(this).hasClass('toggled')) {
                $('[data-block-name="' + $(this).data('blockNameLabel') + '"]').removeClass('block-highlight');
            }
        }).on('click', function() {
            $('[data-block-name-label]')
                .not($(this)).removeClass('toggled');
            $(this).toggleClass('toggled');
            var activeBlock = $('[data-block-name="' + $(this).data('blockNameLabel') + '"]');
            $('[data-block-name]').not(activeBlock)
                .removeClass('block-highlight');
            if (activeBlock.length) {
                $(window).scrollTop(activeBlock.offset().top);
            } else {
                alert('Block not found in layout.');
            }
        });
    });
</script>
